algoritmo "ContarESomar"
// Função :
// Autor :
// Data : 25/01/2022
// Seção de Declarações 
var
   S, N, contador : inteiro
inicio
      S <- 0
      Para contador <- 1 ate 5 faca
               Escreva ("Digite um valor: ")
               Leia (N)
               S <- S+N
               contador <- contador + 1
      FimPara
      Escreval ("A soma de todos os valores é ", S)
fimalgoritmo
